name: Publish VS Code Extension

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Or your desired version
      - name: Update package.json
        run: |
          npm version patch
      - name: Update github
        run: |
          git add package.json
          git commit -m "chore: update package.json for release"
          git push origin master
      - name: Install vsce
        run: npm install -g vsce
      - name: Package the extension
        run: vsce package
      - name: Publish the extension
        run: vsce publish -p ${{ secrets.VSCODE_PAT }}
        env:
          VSCODE_PAT: ${{ secrets.VSCODE_PAT }}
