name: Publish VS Code Extension

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Or your desired version
      - name: Update package.json
        run: |
          git config --global user.email "andrinoff.69@gmail.com"
          git config --global user.name "Drew"
          npm version patch  
      - name: Install vsce
        run: npm install -g vsce
      - name: Package the extension
        run: vsce package
      - name: Publish the extension
        run: vsce publish -p ${{ secrets.VSCODE_PAT }}
        env:
          VSCODE_PAT: ${{ secrets.VSCODE_PAT }}
